### ISSUE TITLE
Is the library still maintained?

### ISSUE THREAD

**Issue by Blunderchips** [filipows/angular-animations#47]

**Comment by filipows** [comment]
Hi @Blunderchips 

yes, it is, would you like anything in particular to be done?

I'm planning to release some minor fixes in the upcoming days.

**Comment by fergardi** [comment]
Is it compatible with Angular 9 Ivy compiler? I'm getting this error:

```
ERROR in ./node_modules/@angular/animations/__ivy_ngcc__/fesm2015/browser.js
Module build failed: Error: ENOENT: no such file or directory, open 'C:\entornos\xxxxxx\workspaces\xxxxxx\node_modules\@angular\animations\__ivy_ngcc__\fesm2015\browser.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
```
